---

- name: "CICD | Ansible Tester | Role {{ repo_name }} | Adding molecule service"
  ansible.builtin.template:
    src: "templates/etc/systemd/system/ansible-test-molecule.service.j2"
    dest: "/etc/systemd/system/ansible-test-molecule-{{ repo_name }}.service"
    owner: 'root'
    group: "{{ tester.user }}"
    mode: 0640
  tags: services

- name: "CICD | Ansible Tester | Role {{ repo_name }} | Adding services"
  ansible.builtin.template:
    src: "templates/etc/systemd/system/ansible-test-default.service.j2"
    dest: "/etc/systemd/system/ansible-test-{{ test }}-{{ repo_name }}.service"
    owner: 'root'
    group: "{{ tester.user }}"
    mode: 0640
  loop_control:
    loop_var: 'test'
  loop:
    - 'yamllint'
    - 'ansiblelint'
    - 'pylint'
  tags: services

- name: "CICD | Ansible Tester | Role {{ repo_name }} | Removing fail-handlers"
  ansible.builtin.file:
    path: "/etc/systemd/system/ansible-test-{{ test }}-{{ repo_name }}-fail.service"
    state: absent
  loop_control:
    loop_var: 'test'
  loop:
    - 'molecule'
    - 'yamllint'
    - 'ansiblelint'
    - 'pylint'
  tags: services

- name: "CICD | Ansible Tester | Role {{ repo_name }} | Adding timers"
  ansible.builtin.template:
    src: "templates/etc/systemd/system/ansible-test-default.timer.j2"
    dest: "/etc/systemd/system/ansible-test-{{ test }}-{{ repo_name }}.timer"
    owner: 'root'
    group: "{{ tester.user }}"
    mode: 0640
  loop_control:
    loop_var: 'test'
  loop:
    - 'molecule'
    - 'yamllint'
    - 'ansiblelint'
    - 'pylint'
  tags: services

- name: "CICD | Ansible Tester | Role {{ repo_name }} | Starting/enabling jobs"
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "ansible-test-{{ item }}-{{ repo_name }}.timer"
    state: started
    enabled: yes
  loop:
    - 'molecule'
    - 'yamllint'
    - 'ansiblelint'
    - 'pylint'
  tags: services

- name: "CICD | Ansible Tester | Role {{ repo_name }} | Adding initial badges"
  ansible.builtin.shell: |
    source "{{ tester.path.venv }}/bin/activate"
    anybadge --label="{{ item.label }}" --value="WAITING" --file="{{ repo_name }}.{{ item.ext }}" --color="#{{ tester.colors.wait }}"
  args:
    executable: '/bin/bash'
    chdir: "{{ tester.path.web }}"
    creates: "{{ tester.path.web }}/{{ repo_name }}.{{ item.ext }}.svg"
  loop:
    - {label: 'YamlLint', ext: 'yamllint'}
    - {label: 'PyLint', ext: 'pylint'}
    - {label: 'Ansible-Lint', ext: 'ansiblelint'}
    - {label: 'Molecule', ext: 'molecule'}
