# docker build -t ansible0guy/molecule:debian-latest --network=host - < Dockerfile_molecule
# for docker systemd config see: https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva

FROM debian:12-slim

ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y systemd systemd-sysv python3 sudo \
    procps less nano net-tools dnsutils iproute2 \
    && apt-get clean

CMD ["/sbin/init"]
